obstacle_range: 2.5
raytrace_range: 3.0

# footprint: [[0, 0]]
# circular robot :)
robot_radius: 0.5
inflation_radius: 0.5 

observation_sources: point_cloud_sensor

point_cloud_sensor: {
  sensor_frame: camera_depth_frame, 
  data_type: PointCloud2, 
  topic: /camera/points, 
  marking: true, 
  clearing: true
}